# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: yaojie
email: limyaojie93@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  NodeJS, Redux/React, RoR for fast prototyping and development!

baseurl: "/" # the subpath of your site, e.g. /blog
url: http://causztic.com # the base hostname & protocol for your site
github_username:  causztic

# Build settings
markdown: kramdown

sass:
  dir: assets/css
  sass_dir: assets/css
  style: compressed

gems: [jekyll-paginate]
paginate: 20
paginate_path: /blog/page:num/
domain_name: 'http://causztic.com'
timezone: 'Asia/Singapore'

# Details for the RSS feed generator
url:            'http://causztic.com'
author:         'yaojie'
authorTwitter:  'causztic'

permalink:       /:year/:title/